apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: centos2009
  namespace: vlan
spec:
  running: true   # 此处设置为true创建vm后即自动创建vmi启动虚拟机
  template:
    metadata:
      labels:
        kubevirt.io/domain: centos2009
      annotations:
        ovn.kubernetes.io/logical_switch: mail263
        ovn.kubernetes.io/ip_address: 192.168.10.190
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: cdromiso
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            model: e1000
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 2Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: iso-centos2009
      - cloudInitNoCloud:
          networkData: |-
            network:
              version: 1
              config:
                - type: physical
                  name: eth0
                  subnets:
                    - type: dhcp
          userData: |-
            #cloud-config
            disable_root: false
            ssh_pwauth: true
            users:
              - default
              - name: root
                lock_passwd: false
                hashed_passwd: $1$4t.w.u.X$BkdPjEOi30r85GpIaTZ8C1
        name: cloudinitdisk