apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: default
spec: 
  configuration:
    developerConfiguration:
      featureGates:
        - HostDisk
        - hyperv
        - CPUNodeDiscovery
